DATA = [
    "The only way to do great work is to love what you do. – Steve Jobs",
    "Success is not the key to happiness. Happiness is the key to success. – Albert Schweitzer",
    "Believe you can and you're halfway there. – Theodore Roosevelt",
    "The best way to predict the future is to create it. – Abraham Lincoln",
    "It always seems impossible until it’s done. – Nelson Mandela",
    "Your limitation—it’s only your imagination.",
    "Push yourself, because no one else is going to do it for you.",
    "Success doesn’t just find you. You have to go out and get it.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Dream it. Wish it. Do it.",
    "Success is the sum of small efforts, repeated day in and day out. – Robert Collier",
    "Don't stop when you're tired. Stop when you're done.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Little things make big days.",
    "It's going to be hard, but hard does not mean impossible.",
    "Don't wait for opportunity. Create it.",
    "Sometimes we're tested not to show our weaknesses, but to discover our strengths.",
    "The key to success is to focus on goals, not obstacles.",
    "Dream bigger. Do bigger.",
    "Stay focused and never give up.",
    "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt",
    "You don’t have to be great to start, but you have to start to be great. – Zig Ziglar",
    "Don’t watch the clock; do what it does. Keep going. – Sam Levenson",
    "The future depends on what you do today. – Mahatma Gandhi",
    "It does not matter how slowly you go as long as you do not stop. – Confucius",
    "Act as if what you do makes a difference. It does. – William James",
    "Success is not how high you have climbed, but how you make a positive difference to the world. – Roy T. Bennett",
    "Life is 10% what happens to us and 90% how we react to it. – Charles R. Swindoll",
    "Don't wish it were easier. Wish you were better. – Jim Rohn",
    "The only impossible journey is the one you never begin. – Tony Robbins",
    "You miss 100% of the shots you don’t take. – Wayne Gretzky",
    "Challenges are what make life interesting and overcoming them is what makes life meaningful. – Joshua Marine",
    "The secret of getting ahead is getting started. – Mark Twain",
    "You are never too old to set another goal or to dream a new dream. – C.S. Lewis",
    "The road to success and the road to failure are almost exactly the same. – Colin R. Davis",
    "Don't be afraid to give up the good to go for the great. – John D. Rockefeller",
    "Start where you are. Use what you have. Do what you can. – Arthur Ashe",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill",
    "It is never too late to be what you might have been. – George Eliot",
    "We may encounter many defeats, but we must not be defeated. – Maya Angelou",
    "You are braver than you believe, stronger than you seem, and smarter than you think. – A.A. Milne",
    "Hardships often prepare ordinary people for an extraordinary destiny. – C.S. Lewis",
    "In the middle of every difficulty lies opportunity. – Albert Einstein",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. – Roy T. Bennett",
    "Everything you can imagine is real. – Pablo Picasso",
    "Opportunities don't happen. You create them. – Chris Grosser",
    "Success is what happens after you have survived all your mistakes. – Anonymous",
    "The only place where success comes before work is in the dictionary. – Vidal Sassoon",
    "Life is what happens when you're busy making other plans. – John Lennon",
    "If you want to lift yourself up, lift up someone else. – Booker T. Washington",
    "The only thing standing between you and your goal is the story you keep telling yourself. – Jordan Belfort",
    "Life is 10% what happens to us and 90% how we react to it. – Charles R. Swindoll",
    "Why don’t skeletons fight each other? They don’t have the guts.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "Why don’t some couples go to the gym? Because some relationships don’t work out.",
    "I’m reading a book on anti-gravity. It’s impossible to put down.",
    "Parallel lines have so much in common. It’s a shame they’ll never meet.",
    "Why don’t oysters donate to charity? Because they are shellfish.",
    "I would tell you a joke about an elevator, but it’s an uplifting experience.",
    "I told my computer I needed a break, and now it won’t stop sending me Kit-Kats.",
    "I’m on a whiskey diet. I’ve lost three days already.",
    "What’s orange and sounds like a parrot? A carrot.",
    "I used to play piano by ear, but now I use my hands.",
    "I’m terrified of elevators, so I’m going to start taking steps to avoid them.",
    "I told my friend 10 jokes to make him laugh. Sadly, no pun in ten did.",
    "Why was the math book sad? Because it had too many problems.",
    "What do you call fake spaghetti? An impasta.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "I couldn’t figure out how to put my seatbelt on. Then it clicked.",
    "I bought some shoes from a drug dealer. I don’t know what he laced them with, but I’ve been tripping all day.",
    "I used to be indecisive, but now I’m not so sure.",
    "What do you call cheese that isn’t yours? Nacho cheese.",
    "What’s brown and sticky? A stick.",
    "What do you get when you cross a snowman and a vampire? Frostbite.",
    "Why do cows have hooves instead of feet? Because they lactose.",
    "What did the grape say when it got stepped on? Nothing, it just let out a little wine.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "Did you hear about the claustrophobic astronaut? He needed a little space.",
    "Why can’t your nose be 12 inches long? Because then it would be a foot.",
    "I’m writing a book on reverse psychology. Don’t buy it.",
    "What do you get when you cross a snowman and a dog? Frostbite.",
    "I tried to catch some fog earlier. I mist.",
    "What did one ocean say to the other ocean? Nothing, they just waved.",
    "I used to have a job as a professional cricket player, but I was stung by the competition.",
    "Why don’t seagulls fly over the bay? Because then they’d be bagels.",
    "What did the 0 say to the 8? Nice belt!",
    "Why was the computer cold? It left its Windows open.",
    "I just burned 1,200 calories. I forgot the pizza in the oven.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "I’m on a seafood diet. I see food and I eat it.",
    "What did one hat say to the other? Stay here, I’m going on ahead!",
    "Why don’t skeletons fight each other? They don’t have the guts.",
    "I have a fear of speed bumps, but I am slowly getting over it.",
    "I told my wife she should embrace her mistakes. She gave me a hug."
]
